AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Toggl Integration Lambda Function

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  CalendarID:
    Type: String
    Description: An environment variable for the Google Calendar ID
    Default: "TEMPLATE! put your calendar id here"
  AuthARN:
    Type: String
    Description: An environment variable for the AUTH arn
    Default: "TEMPLATE! put AWS ARN for GoogleAPICredentials in TogglWebhook secret"
  TogglSIG:
    Type: String
    Description: An environment variable for Toggl Signature
    Default: ""
  TogglAPI:
    Type: String
    Description: An environment variable for Toggl API Token
    Default: ""

Resources:
  TogglWebhookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: webhook_handler.app.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 30
      Architectures:
        - x86_64
      Events:
        TogglWebhook:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /webhook
            Method: post
      Environment:
        Variables:
          GOOGLE_CALENDAR_ID: !Ref CalendarID
          GOOGLE_CALENDAR_AUTH_SECRET_ARN: !Ref AuthARN
          TOGGL_SIGNATURE: !Ref TogglSIG
          TOGGL_API_TOKEN: !Ref TogglAPI
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:TogglWebhook-*


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TogglWebhookApi:
    Description: "API Gateway endpoint URL for Prod stage for Toggl Webhook function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/"
  TogglWebhookFunction:
    Description: "Toggl Webhook Lambda Function ARN"
    Value: !GetAtt TogglWebhookFunction.Arn
  TogglWebhookFunctionIamRole:
    Description: "Implicit IAM Role created for Toggl Webhook function"
    Value: !GetAtt TogglWebhookFunctionRole.Arn
